server:
 port: 8080
mysql:
  host: 127.0.0.0.1
  port: 3306
  user: root
  password: root1234
  dbName: shopducteo
  maxIdleConns: 5
  maxOpenConns: 100
  connMaxLifetime: "3600"
log:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_size: 500 #MB
  max_backups: 3
  max_age: 7 #day
  compress: true
